package com.personalidad.persistencia;

public class PreguntasEnArreglo {

	  public static String[][][] quest = 
{ 
{{"TE GUSTA LA AUTORIDAD" },{"ERES ENTUSIASTA" },{"ERES SENSIBLE" },{"TE GUSTAN LAS INSTRUCCIONES" } },
{{"TOMA EL MANDO" },{"TE ARRIESGAS"},{"ERES LEAL"},{"ERES PRECISO" }},
{{"ERES DETERMINADO" },{ "ERES VISIONARIO" },{"ERES CALMADO"},{"ERES CONSTANTE"}}, 
{{"ERES EMPRENDERDOR"},{ "TE GUSTA HABLAR"},{"TE GUSTA LA RUTINA"},{"ERES PREDECIBLE"}},
{{"ERES COMPETITIVO" },{"ERES PROMOTOR"},{"NO TE GUSTA LOS CAMBIOS"},{"ERES PRACTICO"}}, 
{{"RESUELVES PROBLEMAS" }, { "TE GUSTA LA POPULARIDAD"},{"TE GUSTA DAR" },{"PREFIERES LOS HECHOS"}},
{{"ERES PRODUCTIVO" }, { "ERES AMIGABLE Y BUENO" },{"EVITAS CONFRONTACIONES"},{"ERES PENSANTE" }},
{{"ERES DIRECTO" },{"TE GUSTA LA VARIEDAD"},{"ERES SIMPATICO" },{"ERES PERFECCIONISTA"}},
{{"TOMAS DESICIONES" },{"ERES ESPONTANEO"},{"TE GUSTA LAS RELACIONES PERSONALES"},{"TE GUSTAN LOS DETALLES"}},
{{"ERES PERSISTENTE"},{"ERES INSPIRACIONAL"},{"ERES PACIFICO"},{"ERES ANALITICO"}} 
};
	  
}
